[package]
name = "petals_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
stem = { path = "../../stem", features = ["rt"] }
petals = { path = "../../petals" }
stile = { path = "../../stile" }
taffy = { version = "0.10.1", default-features = false, features = ["alloc", "taffy_tree", "flexbox"] }

[[bin]]
name = "petals_demo"
path = "src/main.rs"
test = false
bench = false
