[workspace]
resolver = "2"
members = [
  # tidy-alphabetical-start
  "thingos/abi",
  "thingos/abi-macros",
  "thingos/bran",
  "compiler/rustc",
  "thingos/drivers/ahci_disk",
  "thingos/drivers/ata_disk",
  "thingos/drivers/chime",
  "thingos/cambium",
  "thingos/drivers/display_bootfb",
  "thingos/drivers/display_fake",
  "thingos/drivers/display_virtio_gpu",
  "thingos/drivers/driver_wasm_host",
  "thingos/drivers/hdaudio",
  "thingos/drivers/hwrng",
  "thingos/drivers/pci_stubd",
  "thingos/drivers/proto_driver_wasm",
  "thingos/drivers/ps2_kbd",
  "thingos/drivers/ps2_mouse",
  "thingos/drivers/rtc_cmos",
  "thingos/drivers/rtl8168d",
  "thingos/drivers/virtio",
  "thingos/drivers/virtio_gpu",
  "thingos/drivers/virtio_netd",
  "thingos/drivers/virtio_sound",
  "thingos/kernel",
  "thingos/libs/fb_common",
  "thingos/libs/ipc_helpers",
  "thingos/libs/llm",
  "thingos/libs/llm_stub",
  "thingos/libs/ollama",
  "src/build_helper",
  "src/rustc-std-workspace/rustc-std-workspace-alloc",
  "src/rustc-std-workspace/rustc-std-workspace-core",
  "src/rustc-std-workspace/rustc-std-workspace-std",
  "src/rustdoc-json-types",
  "thingos",
  "xtask",
  "src/tools/build-manifest",
  "src/tools/bump-stage0",
  "src/tools/cargotest",
  "src/tools/clippy",
  "src/tools/clippy/clippy_dev",
  "src/tools/collect-license-metadata",
  "src/tools/compiletest",
  "src/tools/coverage-dump",
  "src/tools/features-status-dump",
  "src/tools/generate-copyright",
  "src/tools/generate-windows-sys",
  "src/tools/html-checker",
  "src/tools/jsondocck",
  "src/tools/jsondoclint",
  "src/tools/linkchecker",
  "src/tools/lint-docs",
  "src/tools/lld-wrapper",
  "src/tools/llvm-bitcode-linker",
  "src/tools/miri",
  "src/tools/miri/cargo-miri",
  "src/tools/miropt-test-tools",
  "src/tools/opt-dist",
  "src/tools/remote-test-client",
  "src/tools/remote-test-server",
  "src/tools/replace-version-placeholder",
  "src/tools/run-make-support",
  "src/tools/rust-installer",
  "src/tools/rustdoc",
  "src/tools/rustdoc-gui-test",
  "src/tools/rustdoc-themes",
  "src/tools/rustfmt",
  "src/tools/test-float-parse",
  "src/tools/tidy",
  "src/tools/tier-check",
  "src/tools/unicode-table-generator",
  "src/tools/unstable-book-gen",
  "src/tools/wasm-component-ld",
  "src/tools/x",
  "thingos/stem",
  "thingos/stem-macros",
  "tools/bdd",
  "tools/display_proto_tests",
  "tools/thingos_guardrail_tests",
  "tools/pciids",
  "thingos/utils/basename",
  "thingos/bloom",
  "thingos/bristle",
  "thingos/utils/cat",
  "thingos/utils/clear",
  "thingos/utils/cp",
  "thingos/utils/cwd_test",
  "thingos/utils/date",
  "thingos/utils/dirname",
  "thingos/utils/dmesg",
  "thingos/utils/echo",
  "thingos/utils/env",
  "thingos/utils/env_roundtrip",
  "thingos/utils/false",
  "thingos/utils/fetchd",
  "thingos/utils/find",
  "thingos/utils/file",
  "thingos/pistil",
  "thingos/utils/grep",
  "thingos/utils/head",
  "thingos/utils/hello_stdio",
  "thingos/utils/hello_std",
  "thingos/utils/input_echo",
  "thingos/utils/ipc_inbox_demo",
  "thingos/utils/ipc_memfd_demo",
  "thingos/utils/ipc_pipe_demo",
  "thingos/utils/ipc_provider_demo",
  "thingos/utils/ipc_service_demo",
  "thingos/utils/iso9660",
  "thingos/utils/iso9660d",
  "thingos/utils/iso_reader",
  "thingos/utils/kill",
  "thingos/utils/ld_so",
  "thingos/utils/libdl",
  "thingos/utils/ln",
  "thingos/utils/loglevel",
  "thingos/utils/ls",
  "thingos/utils/mkdir",
  "thingos/utils/mv",
  "thingos/utils/netd",
  "thingos/utils/nslookup",
  "thingos/utils/ping",
  "thingos/utils/placed",
  "thingos/utils/poll_mux",
  "thingos/utils/proc_smoke",
  "thingos/utils/ps",
  "thingos/utils/pwd",
  "thingos/utils/reboot",
  "thingos/utils/rm",
  "thingos/utils/rmdir",
  "thingos/utils/setshell",
  "thingos/utils/sh",
  "thingos/utils/show_args",
  "thingos/utils/shutdown",
  "thingos/utils/sleep",
  "thingos/utils/smallsh",
  "thingos/utils/sort",
  "thingos/sprout",
  "thingos/utils/stat",
  "thingos/utils/stdio_demo",
  "thingos/utils/tail",
  "thingos/utils/terminal",
  "thingos/utils/tee",
  "thingos/utils/test_exec",
  "thingos/utils/tests/test_dlopen",
  "thingos/utils/tests/test_dyn_loader",
  "thingos/utils/tests/test_exec_env",
  "thingos/utils/tests/test_fs",
  "thingos/utils/tests/test_futex",
  "thingos/utils/tests/test_thread_std",
  "thingos/utils/tests/test_threads",
  "thingos/utils/tests/test_vm_protect",
  "thingos/utils/tests/test_vm_shared",
  "thingos/utils/time_test",
  "thingos/utils/touch",
  "thingos/utils/top",
  "thingos/utils/uname",
  "thingos/utils/true",
  "thingos/utils/vfs_hello",
  "thingos/utils/wayland_hello",
  "thingos/utils/wc",
  "thingos/utils/yes",
  "thingos/utils/which",
  "thingos/utils/xargs",
  "tools/kindc",
  "vendor/lsv",
  # tidy-alphabetical-end
]

exclude = [
  "build",
  "compiler/rustc_codegen_cranelift",
  "compiler/rustc_codegen_gcc",
  "src/bootstrap",
  "tests/rustdoc-gui",
  # HACK(eddyb) This hardcodes the fact that our CI uses `/checkout/obj`.
  "obj",
]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[profile.bench]
debug = true

[profile.release.package.rustc_thread_pool]
# The rustc fork of Rayon has deadlock detection code which intermittently
# causes overflows in the CI (see https://github.com/rust-lang/rust/issues/90227)
# so we turn overflow checks off for now.
# FIXME: This workaround should be removed once #90227 is fixed.
overflow-checks = false

# These are very thin wrappers around executing lld with the right binary name.
# Basically nothing within them can go wrong without having been explicitly logged anyway.
# We ship these in every rustc tarball and even after compression they add up
# to around 0.6MB of data every user needs to download (and 15MB on disk).
[profile.release.package.lld-wrapper]
debug = 0
strip = true
[profile.release.package.wasm-component-ld-wrapper]
debug = 0
strip = true

# Bigint libraries are slow without optimization, speed up testing
[profile.dev.package.test-float-parse]
opt-level = 3

# Speed up the binary as much as possible
[profile.release.package.test-float-parse]
opt-level = 3
codegen-units = 1
# FIXME: LTO cannot be enabled for binaries in a workspace
# <https://github.com/rust-lang/cargo/issues/9330>
# lto = true

# If you want to use a crate with local modifications, you can set a path or git dependency here.
# For git dependencies, also add your source to ALLOWED_SOURCES in src/tools/tidy/src/extdeps.rs.
[patch.crates-io]
crossterm = { path = "vendor/crossterm" }
libc = { path = "vendor/libc" }
which = { path = "vendor/which" }
dirs = { path = "vendor/dirs" }
dirs-sys = { path = "vendor/dirs-sys" }
errno = { path = "vendor/errno" }
mio = { path = "vendor/mio" }
