#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Description {
    Pressable,
    Textual,
    Focusable,
    ExpressesValue,
    AcceptsInputSequence,
    AcceptsText,
    SubmitsActionRequest,
    Scrollable,
    Container,
    WindowChrome,
    WindowFrame,
    Titlebar,
    Title,
    WindowContent,
    ResizeEdge,
    ChromeButton,
    Perspective,
    Clock,
    ClockFace,
    ClockTime,
    ClockAmPm,
    ClockDate,
    Calculator,
    DisplayPanel,
    ExpressionLine,
    ResultLine,
    KeypadGrid,
    KeypadRow,
    CalcKey,
    DigitKey,
    DecimalKey,
    OperatorKey,
    EqualsKey,
    DangerKey,
    MemoryKey,
    ModeToggle,
    RunBox,
    RunLabel,
    TextField,
    SubmitButton,
    Logogram,
    ApplicationLauncher,
    ApplicationGrid,
    ApplicationRow,
    ApplicationTile,
    ApplicationTitle,
    ApplicationName,
    ApplicationPath,
    ApplicationStatus,
    Showcase,
    ShowcasePanel,
    ShowcaseHeader,
    ShowcaseSwatch,
    ShowcaseStateStrip,
    Desktop,
    Wallpaper,
    /// A full-width pressable list row.  Nodes with this description have
    /// `flex_grow: 1.0` applied by default so they expand to fill the
    /// available main-axis space of their container.  Pair the container with
    /// `align_items: Stretch` to also span the cross-axis.
    ListRow,
}
