#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Description {
    Pressable,
    Textual,
    Focusable,
    ExpressesValue,
    AcceptsInputSequence,
    AcceptsText,
    SubmitsActionRequest,
    Scrollable,
    Container,
    WindowChrome,
    WindowFrame,
    Titlebar,
    Title,
    WindowContent,
    ResizeEdge,
    ChromeButton,
    Perspective,
    Clock,
    ClockFace,
    ClockTime,
    ClockAmPm,
    ClockDate,
    Calculator,
    DisplayPanel,
    ExpressionLine,
    ResultLine,
    KeypadGrid,
    KeypadRow,
    CalcKey,
    DigitKey,
    DecimalKey,
    OperatorKey,
    EqualsKey,
    DangerKey,
    MemoryKey,
    ModeToggle,
    RunBox,
    RunLabel,
    TextField,
    SubmitButton,
    Logogram,
    ApplicationLauncher,
    ApplicationGrid,
    ApplicationRow,
    ApplicationTile,
    ApplicationTitle,
    ApplicationName,
    ApplicationPath,
    ApplicationStatus,
    Showcase,
    ShowcasePanel,
    ShowcaseHeader,
    ShowcaseSwatch,
    ShowcaseStateStrip,
    Desktop,
    Wallpaper,
    ScrollContainer,
    /// A full-width pressable list row.  Nodes with this description expand
    /// to fill the container's cross-axis when the parent uses
    /// `align_items: Stretch` (e.g. a `flex-direction: column` list where
    /// children should span the full container width).
    ///
    /// The [`Description::ListRow`] tag enables targeted CSS-like rules (for
    /// minimum height, padding, etc.) and is recognised by the debug overlay
    /// as a hit region marker alongside [`Description::Pressable`].
    ListRow,
}
