use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::{env, fs};

use pciids::{Mode, build_tables, filter_vendors, parse_pci_ids, render_rust};

fn main() {
    println!("cargo:rustc-check-cfg=cfg(target_os,values(\"thingos\"))");
    println!("cargo:rustc-check-cfg=cfg(target_env,values(\"thingos\"))");
    println!("cargo:rerun-if-env-changed=PCI_IDS_MODE");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let pci_ids_path = manifest_dir.join("../..").join("assets/pci/pci.ids");
    println!("cargo:rerun-if-changed={}", pci_ids_path.display());

    let contents = fs::read_to_string(&pci_ids_path).expect("failed to read assets/pci/pci.ids");

    let parsed = parse_pci_ids(&contents);
    let mode = Mode::from_env(env::var("PCI_IDS_MODE").ok());
    let filtered = filter_vendors(&parsed.vendors, mode);
    let tables = build_tables(&filtered);
    let rust = render_rust(&tables, &parsed.snapshot, mode);

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("pci_ids_gen.rs");
    fs::write(&out_path, rust).expect("failed to write generated PCI ID table");

    build_i18n_catalogs(&manifest_dir);
}

#[derive(Clone, Debug)]
struct TranslationUnit {
    id: String,
    source: String,
    target: String,
}

#[derive(Clone, Debug)]
struct LocaleCatalog {
    locale: String,
    units: Vec<TranslationUnit>,
}

fn build_i18n_catalogs(manifest_dir: &Path) {
    let catalog_dir = manifest_dir.join("i18n/catalogs");
    println!("cargo:rerun-if-changed={}", catalog_dir.display());

    let mut catalogs = Vec::new();
    if let Ok(entries) = fs::read_dir(&catalog_dir) {
        let mut paths = entries
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("xlf"))
            .collect::<Vec<_>>();
        paths.sort();

        for path in paths {
            println!("cargo:rerun-if-changed={}", path.display());
            let xml = fs::read_to_string(&path)
                .unwrap_or_else(|err| panic!("failed to read {}: {}", path.display(), err));
            let fallback_locale =
                path.file_stem().and_then(|stem| stem.to_str()).unwrap_or("en").to_string();
            catalogs.push(parse_xliff_catalog(&xml, fallback_locale));
        }
    }

    if catalogs.is_empty() {
        catalogs.push(LocaleCatalog { locale: "en".to_string(), units: Vec::new() });
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("i18n_catalogs_gen.rs");
    fs::write(&out_path, render_i18n_catalogs(&catalogs))
        .expect("failed to write generated i18n catalog table");

    let extracted_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("i18n_extracted.en.xlf");
    fs::write(&extracted_path, render_extracted_source_xliff(manifest_dir))
        .expect("failed to write extracted i18n source catalog");
}

fn parse_xliff_catalog(xml: &str, fallback_locale: String) -> LocaleCatalog {
    let locale = attr_value(xml, "target-language")
        .or_else(|| attr_value(xml, "trgLang"))
        .unwrap_or(fallback_locale);
    let mut units = Vec::new();
    let mut rest = xml;

    while let Some(start_idx) = rest.find("<trans-unit") {
        rest = &rest[start_idx..];
        let Some(open_end) = rest.find('>') else { break };
        let open_tag = &rest[..=open_end];
        let Some(close_idx) = rest.find("</trans-unit>") else { break };
        let body = &rest[open_end + 1..close_idx];
        let source = tag_text(body, "source").unwrap_or_default();
        let target =
            tag_text(body, "target").filter(|s| !s.is_empty()).unwrap_or_else(|| source.clone());
        let id =
            attr_value(open_tag, "id").filter(|s| !s.is_empty()).unwrap_or_else(|| source.clone());
        if !source.is_empty() {
            units.push(TranslationUnit { id, source, target });
        }
        rest = &rest[close_idx + "</trans-unit>".len()..];
    }

    LocaleCatalog { locale, units }
}

fn attr_value(input: &str, name: &str) -> Option<String> {
    let needle = format!("{}=\"", name);
    let start = input.find(&needle)? + needle.len();
    let end = input[start..].find('"')?;
    Some(unescape_xml(&input[start..start + end]))
}

fn tag_text(input: &str, tag: &str) -> Option<String> {
    let open = format!("<{}>", tag);
    let close = format!("</{}>", tag);
    let start = input.find(&open)? + open.len();
    let end = input[start..].find(&close)?;
    Some(unescape_xml(input[start..start + end].trim()))
}

fn render_i18n_catalogs(catalogs: &[LocaleCatalog]) -> String {
    let default_locale =
        catalogs.iter().find(|c| c.locale == "en").unwrap_or(&catalogs[0]).locale.as_str();
    let mut out = String::new();

    out.push_str("// @generated by thingos/stem/build.rs\n");
    out.push_str(&format!("pub const DEFAULT_LOCALE: &str = {:?};\n", default_locale));
    out.push_str("pub const LOCALE_IDS: &[&str] = &[\n");
    for catalog in catalogs {
        out.push_str(&format!("    {:?},\n", catalog.locale));
    }
    out.push_str("];\n\n");

    let mut table_names = Vec::new();
    for catalog in catalogs {
        let table_name = format!("{}_CATALOG", rust_ident(&catalog.locale).to_uppercase());
        table_names.push(table_name.clone());
        out.push_str(&format!("pub const {}: &[(&str, &str)] = &[\n", table_name));
        let mut entries = BTreeMap::new();
        for unit in &catalog.units {
            entries.insert(unit.id.as_str(), unit.target.as_str());
            entries.insert(unit.source.as_str(), unit.target.as_str());
        }
        for (key, target) in entries {
            out.push_str(&format!("    ({:?}, {:?}),\n", key, target));
        }
        out.push_str("];\n\n");
    }

    out.push_str("pub const CATALOGS: &[(&str, &[(&str, &str)])] = &[\n");
    for (catalog, table_name) in catalogs.iter().zip(table_names.iter()) {
        out.push_str(&format!("    ({:?}, {}),\n", catalog.locale, table_name));
    }
    out.push_str("];\n");
    out
}

fn render_extracted_source_xliff(manifest_dir: &Path) -> String {
    let source_root = manifest_dir.parent().unwrap_or(manifest_dir);
    let mut units = BTreeMap::new();
    collect_source_strings(source_root, &mut units);

    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str("<xliff version=\"1.2\" xmlns=\"urn:oasis:names:tc:xliff:document:1.2\">\n");
    out.push_str("  <file original=\"thingos\" source-language=\"en\" datatype=\"plaintext\">\n");
    out.push_str("    <body>\n");
    for (source, note) in units {
        out.push_str(&format!("      <trans-unit id=\"{}\">\n", escape_xml_attr(&source)));
        out.push_str(&format!("        <source>{}</source>\n", escape_xml_text(&source)));
        if let Some(note) = note {
            out.push_str(&format!("        <note>{}</note>\n", escape_xml_text(&note)));
        }
        out.push_str("      </trans-unit>\n");
    }
    out.push_str("    </body>\n");
    out.push_str("  </file>\n");
    out.push_str("</xliff>\n");
    out
}

fn collect_source_strings(root: &Path, units: &mut BTreeMap<String, Option<String>>) {
    let Ok(entries) = fs::read_dir(root) else { return };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.file_name().and_then(|name| name.to_str()) == Some("target") {
            continue;
        }
        if path.is_dir() {
            collect_source_strings(&path, units);
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }
        if path.ends_with("build.rs")
            || path.components().any(|component| component.as_os_str() == "target")
            || path.ends_with("stem/src/i18n/mod.rs")
        {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let Ok(contents) = fs::read_to_string(&path) else { continue };
        extract_macro_literals(&contents, units);
    }
}

fn extract_macro_literals(contents: &str, units: &mut BTreeMap<String, Option<String>>) {
    for macro_name in ["stem::t!", "stem::tr!", "stem::tf!"] {
        let mut search = contents;
        while let Some(idx) = search.find(macro_name) {
            let after = &search[idx + macro_name.len()..];
            let Some(paren_idx) = after.find('(') else { break };
            let body = &after[paren_idx + 1..];
            let literals = string_literals(body, 2);
            let Some(first) = literals.first() else {
                search = &body[body.len().min(1)..];
                continue;
            };
            let source = if literals.len() > 1 && looks_like_legacy_key(first) {
                literals[1].clone()
            } else {
                first.clone()
            };
            let note = note_literal(body);
            units.entry(source).or_insert(note);
            search = &body[body.len().min(1)..];
        }
    }
}

fn string_literals(input: &str, limit: usize) -> Vec<String> {
    let mut literals = Vec::new();
    let mut rest = input;
    while literals.len() < limit {
        let Some(start) = rest.find('"') else { break };
        let Some((value, consumed)) = parse_string_literal(&rest[start..]) else { break };
        literals.push(value);
        rest = &rest[start + consumed..];
    }
    literals
}

fn first_string_literal(input: &str) -> Option<String> {
    let start = input.find('"')?;
    parse_string_literal(&input[start..]).map(|(value, _)| value)
}

fn looks_like_legacy_key(value: &str) -> bool {
    value.contains('.')
        && value.chars().all(|ch| ch.is_ascii_alphanumeric() || ch == '.' || ch == '_' || ch == '-')
}

fn note_literal(input: &str) -> Option<String> {
    let note_idx = input.find("note:")?;
    first_string_literal(&input[note_idx + "note:".len()..])
}

fn parse_string_literal(input: &str) -> Option<(String, usize)> {
    let mut chars = input.char_indices();
    if chars.next()?.1 != '"' {
        return None;
    }
    let mut out = String::new();
    let mut escaped = false;
    for (idx, ch) in chars {
        if escaped {
            match ch {
                'n' => out.push('\n'),
                'r' => out.push('\r'),
                't' => out.push('\t'),
                '"' => out.push('"'),
                '\\' => out.push('\\'),
                _ => out.push(ch),
            }
            escaped = false;
        } else if ch == '\\' {
            escaped = true;
        } else if ch == '"' {
            return Some((out, idx + 1));
        } else {
            out.push(ch);
        }
    }
    None
}

fn rust_ident(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    out
}

fn escape_xml_text(value: &str) -> String {
    value.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

fn escape_xml_attr(value: &str) -> String {
    escape_xml_text(value).replace('"', "&quot;")
}

fn unescape_xml(value: &str) -> String {
    value
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&gt;", ">")
        .replace("&lt;", "<")
        .replace("&amp;", "&")
}
