[package]
name = "bloom"
version = "0.1.0"
edition = "2021"

[dependencies]
stem = { path = "../stem", features = ["rt", "global-alloc"] }
abi = { path = "../abi" }
libdl = { path = "../utils/libdl" }
pistil = { path = "../pistil" }
spin = "0.9"

[[bin]]
name = "bloom"
path = "src/main.rs"
test = false
doctest = false
