[package]
name = "display_virtio_gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
stem = { path = "../../stem", features = ["rt"] }
abi = { path = "../../abi" }
accel2d_cpu = { path = "../../libs/accel2d_cpu" }
virtio_gpu = { path = "../virtio_gpu" }
ipc_helpers = { path = "../../libs/ipc_helpers" }
