use std::collections::BTreeMap;
use std::path::PathBuf;
use std::{env, fs};

#[derive(Clone, Debug)]
struct TranslationUnit {
    id: String,
    source: String,
    target: String,
}

#[derive(Clone, Debug)]
struct LocaleCatalog {
    locale: String,
    units: Vec<TranslationUnit>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let catalog_dir = manifest_dir.join("i18n/catalogs");
    println!("cargo:rerun-if-changed={}", catalog_dir.display());

    let mut catalogs = Vec::new();
    if let Ok(entries) = fs::read_dir(&catalog_dir) {
        let mut paths = entries
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("xlf"))
            .collect::<Vec<_>>();
        paths.sort();

        for path in paths {
            println!("cargo:rerun-if-changed={}", path.display());
            let xml = fs::read_to_string(&path)
                .unwrap_or_else(|err| panic!("failed to read {}: {}", path.display(), err));
            let fallback_locale =
                path.file_stem().and_then(|stem| stem.to_str()).unwrap_or("la").to_string();
            catalogs.push(parse_xliff_catalog(&xml, fallback_locale));
        }
    }

    if catalogs.is_empty() {
        catalogs.push(LocaleCatalog { locale: "la".to_string(), units: Vec::new() });
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("kernel_i18n_catalogs_gen.rs");
    fs::write(&out_path, render_i18n_catalogs(&catalogs))
        .expect("failed to write generated kernel i18n catalog table");
}

fn parse_xliff_catalog(xml: &str, fallback_locale: String) -> LocaleCatalog {
    let locale = attr_value(xml, "target-language")
        .or_else(|| attr_value(xml, "trgLang"))
        .unwrap_or(fallback_locale);
    let mut units = Vec::new();
    let mut rest = xml;

    while let Some(start_idx) = rest.find("<trans-unit") {
        rest = &rest[start_idx..];
        let Some(open_end) = rest.find('>') else { break };
        let open_tag = &rest[..=open_end];
        let Some(close_idx) = rest.find("</trans-unit>") else { break };
        let body = &rest[open_end + 1..close_idx];
        let source = tag_text(body, "source").unwrap_or_default();
        let target =
            tag_text(body, "target").filter(|s| !s.is_empty()).unwrap_or_else(|| source.clone());
        let id =
            attr_value(open_tag, "id").filter(|s| !s.is_empty()).unwrap_or_else(|| source.clone());
        if !source.is_empty() {
            units.push(TranslationUnit { id, source, target });
        }
        rest = &rest[close_idx + "</trans-unit>".len()..];
    }

    LocaleCatalog { locale, units }
}

fn attr_value(input: &str, name: &str) -> Option<String> {
    let needle = format!("{}=\"", name);
    let start = input.find(&needle)? + needle.len();
    let end = input[start..].find('"')?;
    Some(unescape_xml(&input[start..start + end]))
}

fn tag_text(input: &str, tag: &str) -> Option<String> {
    let open = format!("<{}>", tag);
    let close = format!("</{}>", tag);
    let start = input.find(&open)? + open.len();
    let end = input[start..].find(&close)?;
    Some(unescape_xml(input[start..start + end].trim()))
}

fn render_i18n_catalogs(catalogs: &[LocaleCatalog]) -> String {
    let default_locale =
        catalogs.iter().find(|c| c.locale == "la").unwrap_or(&catalogs[0]).locale.as_str();
    let mut out = String::new();

    out.push_str("// @generated by thingos/kernel/build.rs\n");
    out.push_str(&format!("pub const DEFAULT_LOCALE: &str = {:?};\n", default_locale));
    out.push_str("pub const LOCALE_IDS: &[&str] = &[\n");
    for catalog in catalogs {
        out.push_str(&format!("    {:?},\n", catalog.locale));
    }
    out.push_str("];\n\n");

    let mut table_names = Vec::new();
    for catalog in catalogs {
        let table_name = format!("{}_CATALOG", rust_ident(&catalog.locale).to_uppercase());
        table_names.push(table_name.clone());
        out.push_str(&format!("pub const {}: &[(&str, &str)] = &[\n", table_name));
        let mut entries = BTreeMap::new();
        for unit in &catalog.units {
            entries.insert(unit.id.as_str(), unit.target.as_str());
            entries.insert(unit.source.as_str(), unit.target.as_str());
        }
        for (key, target) in entries {
            out.push_str(&format!("    ({:?}, {:?}),\n", key, target));
        }
        out.push_str("];\n\n");
    }

    out.push_str("pub const CATALOGS: &[(&str, &[(&str, &str)])] = &[\n");
    for (catalog, table_name) in catalogs.iter().zip(table_names.iter()) {
        out.push_str(&format!("    ({:?}, {}),\n", catalog.locale, table_name));
    }
    out.push_str("];\n");
    out
}

fn rust_ident(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    if out.chars().next().map(|ch| ch.is_ascii_digit()).unwrap_or(true) {
        out.insert(0, '_');
    }
    out
}

fn unescape_xml(input: &str) -> String {
    input
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
}
