//! Wayland server — runs in a dedicated thread using `ServiceLoop`.
//!
//! # Architecture
//!
//! The Wayland server is a separate task (spawned via
//! `stem::thread::spawn_with_arg`).  It:
//!
//! 1. Creates a `ServiceLoop` backed by its own process inbox.
//! 2. Binds a `AF_UNIX SOCK_STREAM` socket at `/run/wayland-0`.
//! 3. Registers the accept socket as a secondary `ServiceLoop` source.
//! 4. On each new connection (`accept`), adds the client socket as another
//!    secondary source.
//! 5. Dispatches Wayland wire messages to [`dispatch`].
//! 6. Sends IPC commands to the main bloom thread via a port and receives
//!    frame-done / buffer-release events back.
//!
//! # Communication with the main thread
//!
//! Wayland → Main: `cmd_write` port handle (see [`ipc`]).
//! Main → Wayland: `evt_read_fd` VFS fd (readable when events are available).

pub mod client;
pub mod dispatch;
pub mod ipc;
pub mod wire;

use alloc::boxed::Box;
use alloc::collections::BTreeMap;
use alloc::string::String;
use alloc::vec::Vec;

use stem::service_loop::{ServiceEvent, ServiceLoop};
use stem::syscall::socket::{accept, bind, listen, recvmsg, socket};
use stem::syscall::socket_domain::AF_UNIX;
use stem::syscall::socket_type::SOCK_STREAM;
use stem::syscall::vfs::{vfs_close, vfs_mkdir, vfs_poll, vfs_read, vfs_unlink};
use stem::wait_set::WaitToken;
use stem::{debug, info, warn};

use self::client::WaylandClient;

pub const WAYLAND_SOCKET_PATH: &str = "/run/wayland-0";
const MAX_BACKLOG: usize = 8;
const MAX_MAIN_EVENTS_PER_DRAIN: usize = 64;

fn stream_readable(fd: u32) -> bool {
    let mut pollfd = [abi::syscall::PollHandle {
        handle: fd as i32,
        events: abi::syscall::poll_flags::POLLIN,
        revents: 0,
    }];
    match vfs_poll(&mut pollfd, 0) {
        Ok(n) if n > 0 => pollfd[0].revents & abi::syscall::poll_flags::POLLIN != 0,
        _ => false,
    }
}

/// Initialization parameters passed from the main thread to the Wayland
/// server thread.
pub struct WaylandThreadArgs {
    /// Port write handle used to send IPC commands to the main bloom thread.
    pub cmd_write: u32,
    /// VFS fd for receiving IPC events from the main bloom thread.
    pub evt_read_fd: u32,
    /// Primary display output info (resolution, refresh rate).
    pub output: crate::display::OutputInfo,
}

/// Thread entry point.  Called by `stem::thread::spawn_with_arg`.
///
/// # Safety
///
/// `arg` must be a valid pointer to a `Box<WaylandThreadArgs>` that was
/// created by the calling thread and will not be accessed after the spawn.
pub extern "C" fn wayland_thread_entry(arg: usize) -> ! {
    let args = unsafe { *Box::from_raw(arg as *mut WaylandThreadArgs) };
    WaylandServer::run(args)
}

// ── WaylandServer ────────────────────────────────────────────────────────────

struct WaylandServer {
    /// ServiceLoop driving the event loop.
    svc: ServiceLoop,
    /// Port write handle for sending commands to the main bloom thread.
    cmd_write: u32,
    /// Token for the event FD (main → wayland).
    evt_tok: WaitToken,
    /// The accept socket FD.
    accept_fd: u32,
    /// Token for the accept socket.
    accept_tok: WaitToken,
    /// Map: ServiceLoop token → WaylandClient.
    clients: BTreeMap<WaitToken, WaylandClient>,
    /// Counter for synthetic surface keys (used for alloc_bloom_surface).
    next_surface_key: u32,
    /// VFS fd for receiving events from the main thread.
    evt_read_fd: u32,
    /// Accumulated main-thread event bytes awaiting fixed-size framing.
    evt_rx_buf: Vec<u8>,
    /// Monotonic serial for input and protocol events generated by this compositor.
    next_serial: u32,
    /// Primary display output info forwarded from the main thread.
    output: crate::display::OutputInfo,
    /// Token of the client that currently owns the clipboard selection.
    clipboard_owner: Option<WaitToken>,
    /// wl_data_source object ID in the clipboard owner client.
    clipboard_source_obj: u32,
    /// MIME types advertised by the current clipboard selection.
    clipboard_mime_types: Vec<String>,
    /// Counter for server-assigned Wayland object IDs (range [0xFF000001, 0xFFFFFFFF]).
    next_server_id: u32,
}

impl WaylandServer {
    fn run(args: WaylandThreadArgs) -> ! {
        let _ = stem::thread::set_name(b"wayland-server");
        info!("wayland-server: starting");

        // ── ServiceLoop ───────────────────────────────────────────────────
        let mut svc = match ServiceLoop::new(256) {
            Ok(s) => s,
            Err(e) => {
                warn!("wayland-server: ServiceLoop::new failed: {:?}", e);
                loop {
                    stem::sleep_ms(1000);
                }
            }
        };

        // ── Register event FD (main → wayland) ───────────────────────────
        let evt_tok = match svc.add_fd_readable(args.evt_read_fd) {
            Ok(t) => t,
            Err(e) => {
                warn!("wayland-server: failed to register evt_read_fd: {:?}", e);
                loop {
                    stem::sleep_ms(1000);
                }
            }
        };

        // ── Bind Unix domain socket ───────────────────────────────────────
        let _ = vfs_mkdir("/run");
        // Remove any stale socket file.
        let _ = vfs_unlink(WAYLAND_SOCKET_PATH);

        let accept_fd = match socket(AF_UNIX, SOCK_STREAM, 0) {
            Ok(fd) => fd,
            Err(e) => {
                warn!("wayland-server: socket() failed: {:?}", e);
                loop {
                    stem::sleep_ms(1000);
                }
            }
        };

        if let Err(e) = bind(accept_fd, WAYLAND_SOCKET_PATH) {
            warn!("wayland-server: bind({}) failed: {:?}", WAYLAND_SOCKET_PATH, e);
            loop {
                stem::sleep_ms(1000);
            }
        }

        if let Err(e) = listen(accept_fd, MAX_BACKLOG) {
            warn!("wayland-server: listen() failed: {:?}", e);
            loop {
                stem::sleep_ms(1000);
            }
        }

        let accept_tok = match svc.add_fd_readable(accept_fd) {
            Ok(t) => t,
            Err(e) => {
                warn!("wayland-server: failed to register accept_fd: {:?}", e);
                loop {
                    stem::sleep_ms(1000);
                }
            }
        };

        info!("wayland-server: listening on {}", WAYLAND_SOCKET_PATH);
        if args.output.supports_dmabuf {
            info!(
                "wayland-server: advertising globals wl_compositor wl_shm xdg_wm_base wl_seat wl_output wl_subcompositor wl_data_device_manager zwp_linux_dmabuf_v1"
            );
        } else {
            info!(
                "wayland-server: advertising globals wl_compositor wl_shm xdg_wm_base wl_seat wl_output wl_subcompositor wl_data_device_manager"
            );
        }

        let mut server = WaylandServer {
            svc,
            cmd_write: args.cmd_write,
            evt_tok,
            accept_fd,
            accept_tok,
            clients: BTreeMap::new(),
            next_surface_key: 1,
            evt_read_fd: args.evt_read_fd,
            evt_rx_buf: Vec::new(),
            next_serial: 1,
            output: args.output,
            clipboard_owner: None,
            clipboard_source_obj: 0,
            clipboard_mime_types: Vec::new(),
            next_server_id: 0xFF00_0001,
        };

        server.event_loop()
    }

    fn event_loop(&mut self) -> ! {
        let mut evt_buf = [0u8; 128];

        loop {
            let event = match self.svc.next_event(Some(stem::time::Duration::from_millis(10))) {
                Ok(ev) => ev,
                Err(e) => {
                    warn!("wayland-server: next_event error: {:?}", e);
                    stem::sleep_ms(10);
                    continue;
                }
            };

            match event {
                ServiceEvent::Message { .. } => {
                    // Control-plane inbox messages are not used by the Wayland server.
                }

                ServiceEvent::Ready { token, event: ev } if ev.is_readable() => {
                    if token == self.accept_tok {
                        self.handle_accept();
                    } else if token == self.evt_tok {
                        // Events from main thread (buffer releases, frame dones).
                        loop {
                            match vfs_read(self.evt_read_fd, &mut evt_buf) {
                                Ok(0) | Err(_) => break,
                                Ok(n) => self.evt_rx_buf.extend_from_slice(&evt_buf[..n]),
                            }
                        }
                        self.drain_main_events();
                    } else {
                        // Client socket.
                        self.handle_client_readable(token);
                    }
                }

                ServiceEvent::Ready { token, event: ev } if ev.is_hangup() || ev.is_error() => {
                    // Client or accept socket closed.
                    if token != self.accept_tok && token != self.evt_tok {
                        self.remove_client(token);
                    }
                }

                ServiceEvent::InboxClosed => {
                    info!("wayland-server: inbox closed, shutting down");
                    loop {
                        stem::sleep_ms(1000);
                    }
                }

                ServiceEvent::Timeout => {
                    self.drain_main_events();
                    self.drain_clients();
                }
                ServiceEvent::Ready { .. } => {}
            }
        }
    }

    fn drain_clients(&mut self) {
        let tokens: Vec<WaitToken> = self.clients.keys().copied().collect();
        for token in tokens {
            self.handle_client_readable(token);
        }
    }

    fn drain_main_events(&mut self) {
        let mut consumed = 0usize;
        let mut handled = 0usize;
        let mut latest_pointer_motion: Option<[u8; 20]> = None;

        while consumed < self.evt_rx_buf.len() {
            if handled >= MAX_MAIN_EVENTS_PER_DRAIN {
                break;
            }
            let Some(event_len) = wayland_event_len(&self.evt_rx_buf[consumed..]) else {
                break;
            };
            if consumed + event_len > self.evt_rx_buf.len() {
                break;
            }

            let event_start = consumed;
            let event_end = consumed + event_len;
            let event_type = self.evt_rx_buf[event_start];
            if event_type == ipc::WEVT_POINTER_MOTION && event_len == 20 {
                let mut motion = [0u8; 20];
                motion.copy_from_slice(&self.evt_rx_buf[event_start..event_end]);
                latest_pointer_motion = Some(motion);
            } else {
                let event = self.evt_rx_buf[event_start..event_end].to_vec();
                if let Some(motion) = latest_pointer_motion.take() {
                    self.handle_main_event(&motion);
                    handled += 1;
                    if handled >= MAX_MAIN_EVENTS_PER_DRAIN {
                        break;
                    }
                }
                self.handle_main_event(&event);
                handled += 1;
            }
            consumed += event_len;
        }

        if handled < MAX_MAIN_EVENTS_PER_DRAIN {
            if let Some(motion) = latest_pointer_motion {
                self.handle_main_event(&motion);
            }
        }

        if consumed > 0 {
            self.evt_rx_buf.drain(..consumed);
        }
    }

    // ── Accept ───────────────────────────────────────────────────────────

    fn handle_accept(&mut self) {
        match accept(self.accept_fd) {
            Ok(client_fd) => {
                let tok = match self.svc.add_fd_readable(client_fd) {
                    Ok(t) => t,
                    Err(e) => {
                        warn!("wayland-server: failed to register client fd: {:?}", e);
                        let _ = vfs_close(client_fd);
                        return;
                    }
                };
                let client = WaylandClient::new(client_fd, self.next_surface_key);
                self.next_surface_key += 100;
                self.clients.insert(tok, client);
                debug!("wayland-server: new client fd={}", client_fd);
                for _ in 0..20 {
                    stem::sleep_ms(5);
                    self.handle_client_readable(tok);
                }
            }
            Err(e) => {
                warn!("wayland-server: accept() failed: {:?}", e);
            }
        }
    }

    // ── Client read ──────────────────────────────────────────────────────

    fn handle_client_readable(&mut self, token: WaitToken) {
        // Phase 1: read bytes while client is still in the map.
        let client_fd = match self.clients.get(&token) {
            Some(c) => c.fd,
            None => return,
        };

        let mut tmp = [0u8; 4096];
        let mut fds = [0u32; 8];
        let mut new_bytes: Vec<u8> = Vec::new();
        let mut dead = false;
        let mut read_sendmsg_packet = false;
        loop {
            match recvmsg(client_fd, &mut tmp, &mut fds) {
                Ok((n, h_count)) => {
                    read_sendmsg_packet = true;
                    new_bytes.extend_from_slice(&tmp[..n]);
                    if let Some(client) = self.clients.get_mut(&token) {
                        for fd in fds.iter().take(h_count) {
                            client.pending_fds.push_back(*fd);
                        }
                    }
                }
                Err(abi::errors::Errno::EAGAIN) => break,
                Err(_) => {
                    dead = true;
                    break;
                }
            }
        }

        if !read_sendmsg_packet && stream_readable(client_fd) {
            match vfs_read(client_fd, &mut tmp) {
                Ok(0) => {
                    dead = true;
                }
                Ok(n) => new_bytes.extend_from_slice(&tmp[..n]),
                Err(abi::errors::Errno::EAGAIN) => {}
                Err(_) => {
                    dead = true;
                }
            }
        }

        if dead {
            self.remove_client(token);
            return;
        }

        // Phase 2: take client out of the map to allow disjoint field access.
        let mut client = match self.clients.remove(&token) {
            Some(c) => c,
            None => return,
        };
        client.recv_buf.extend_from_slice(&new_bytes);

        // Dispatch all complete messages.
        let mut consumed = 0usize;
        loop {
            match wire::decode_one(&client.recv_buf[consumed..]) {
                None => break,
                Some((msg, sz)) => {
                    consumed += sz;
                    let mut blossom =
                        core::mem::replace(&mut client.blossom, blossom::Blossom::new());
                    let cmds = dispatch::dispatch(
                        &msg,
                        &mut client,
                        &mut blossom,
                        self.cmd_write,
                        &mut self.next_surface_key,
                        &self.output,
                    );
                    client.blossom = blossom;
                    for cmd in cmds {
                        let _ = stem::syscall::port_send_all(self.cmd_write, &cmd);
                    }
                }
            }
        }

        // Remove consumed bytes.
        client.recv_buf.drain(..consumed);

        // Extract clipboard side-effects before reinserting the client.
        let pending_clip = client.pending_clipboard_set.take();
        let pending_recv = client.pending_offer_receive.take();

        // Reinsert client.
        self.clients.insert(token, client);

        // Process clipboard set_selection broadcast.
        if let Some((source_obj, mime_types)) = pending_clip {
            self.handle_clipboard_set(token, source_obj, mime_types);
        }

        // Process data_offer.receive fd routing.
        if let Some((mime_type, write_fd)) = pending_recv {
            self.handle_offer_receive(write_fd, mime_type);
        }
    }

    // ── Main thread events ───────────────────────────────────────────────

    fn handle_main_event(&mut self, data: &[u8]) {
        if data.is_empty() {
            return;
        }
        match data[0] {
            ipc::WEVT_BUFFER_RELEASE => {
                if data.len() < 8 {
                    return;
                }
                let wl_buf_key = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                // Find which client owns this key and send wl_buffer.release.
                for client in self.clients.values_mut() {
                    if let Some(&buf_obj) = client.buf_key_to_obj.get(&wl_buf_key) {
                        // wl_buffer.release opcode = 0 (no payload)
                        client.send(buf_obj, 0, &[]);
                        client.buf_key_to_obj.remove(&wl_buf_key);
                        break;
                    }
                }
            }
            ipc::WEVT_FRAME_DONE => {
                if data.len() < 12 {
                    return;
                }
                let bloom_surface_id = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let timestamp_ms = u32::from_ne_bytes(data[8..12].try_into().unwrap_or([0; 4]));
                // Best-effort software presentation timestamp: we don't have
                // ns precision in WEVT_FRAME_DONE (and no real vblank), so
                // re-sample the monotonic clock here for `presented`.
                // This intentionally drifts slightly from the main thread's
                // `FRAME_DONE` timestamp; replace with true vblank time when
                // real-vsync timing lands (see related audit issue).
                let presented_ns = stem::time::monotonic_ns();
                let refresh_ns: u32 = if self.output.refresh_mhz > 0 {
                    // refresh_mhz is in milli-Hz; refresh_ns = 1e9 * 1e3 / mHz.
                    (1_000_000_000_000u64 / self.output.refresh_mhz as u64) as u32
                } else {
                    0
                };
                for client in self.clients.values_mut() {
                    // fire_frame_cbs returns the IDs that were fired; we only
                    // need the side-effect (sending wl_callback.done), so the
                    // list is intentionally dropped.
                    let fired = client.fire_frame_cbs(bloom_surface_id, timestamp_ms);
                    if !fired.is_empty() {
                        stem::trace!(
                            "wayland-server: frame callback done surface={} ts={}ms callbacks={}",
                            bloom_surface_id,
                            timestamp_ms,
                            fired.len()
                        );
                    }
                    let output_obj = client.output_object();
                    let presented = client.fire_presentation_feedbacks_presented(
                        bloom_surface_id,
                        presented_ns,
                        refresh_ns,
                        output_obj,
                    );
                    if !presented.is_empty() {
                        stem::trace!(
                            "wayland-server: wp_presentation_feedback.presented surface={} ts_ns={} feedbacks={}",
                            bloom_surface_id,
                            presented_ns,
                            presented.len()
                        );
                    }
                }
            }
            ipc::WEVT_CONFIGURE_SURFACE => {
                if data.len() < 16 {
                    return;
                }
                let bloom_surface_id = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let width = i32::from_ne_bytes(data[8..12].try_into().unwrap_or([0; 4]));
                let height = i32::from_ne_bytes(data[12..16].try_into().unwrap_or([0; 4]));
                let resizing = data.get(1).copied().unwrap_or(0) != 0;
                for client in self.clients.values_mut() {
                    if client.xdg_toplevel_for_bloom_surface(bloom_surface_id).is_none() {
                        continue;
                    }
                    let states = if resizing {
                        alloc::vec![blossom::XdgToplevelStateAtom::Resizing]
                    } else {
                        alloc::vec![]
                    };
                    if let Some(cmds) = client.blossom.configure_toplevel_for_surface(
                        bloom_surface_id,
                        width,
                        height,
                        states,
                    ) {
                        dispatch::send_blossom_commands(client, &cmds, self.cmd_write);
                        info!(
                            "wayland-server: configured surface={} size={}x{} resizing={}",
                            bloom_surface_id, width, height, resizing
                        );
                    }
                    break;
                }
            }
            ipc::WEVT_TOPLEVEL_ACTION => {
                if data.len() < 16 {
                    return;
                }
                let action = data.get(1).copied().unwrap_or(0);
                let bloom_surface_id = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let width = i32::from_ne_bytes(data[8..12].try_into().unwrap_or([0; 4]));
                let height = i32::from_ne_bytes(data[12..16].try_into().unwrap_or([0; 4]));
                // Any toplevel action (close, minimize, maximize, fullscreen)
                // should dismiss open popups — the toplevel surface is not a
                // popup surface so dismiss_popups_if_outside will fire for all
                // active popups regardless of which toplevel triggered the action.
                self.dismiss_popups_if_outside(bloom_surface_id);
                for client in self.clients.values_mut() {
                    if client.xdg_toplevel_for_bloom_surface(bloom_surface_id).is_none() {
                        continue;
                    }
                    match action {
                        ipc::TOPLEVEL_ACTION_CLOSE => {
                            if let Some(cmds) =
                                client.blossom.close_toplevel_for_surface(bloom_surface_id)
                            {
                                dispatch::send_blossom_commands(client, &cmds, self.cmd_write);
                                info!(
                                    "wayland-server: sent xdg_toplevel.close surface={}",
                                    bloom_surface_id
                                );
                            }
                        }
                        ipc::TOPLEVEL_ACTION_MINIMIZE => {
                            // xdg-shell has no compositor-to-client minimized state event.
                            // Bloom hides the surface; the Wayland side only records the action.
                            info!(
                                "wayland-server: minimized surface={} via compositor chrome",
                                bloom_surface_id
                            );
                        }
                        ipc::TOPLEVEL_ACTION_MAXIMIZE => {
                            if let Some(cmds) = client.blossom.configure_toplevel_for_surface(
                                bloom_surface_id,
                                width,
                                height,
                                alloc::vec![blossom::XdgToplevelStateAtom::Maximized],
                            ) {
                                dispatch::send_blossom_commands(client, &cmds, self.cmd_write);
                                info!(
                                    "wayland-server: maximized surface={} size={}x{}",
                                    bloom_surface_id, width, height
                                );
                            }
                        }
                        ipc::TOPLEVEL_ACTION_FULLSCREEN => {
                            if let Some(cmds) = client.blossom.configure_toplevel_for_surface(
                                bloom_surface_id,
                                width,
                                height,
                                alloc::vec![blossom::XdgToplevelStateAtom::Fullscreen],
                            ) {
                                dispatch::send_blossom_commands(client, &cmds, self.cmd_write);
                                info!(
                                    "wayland-server: fullscreen surface={} size={}x{}",
                                    bloom_surface_id, width, height
                                );
                            }
                        }
                        _ => {}
                    }
                    break;
                }
            }
            ipc::WEVT_POINTER_ENTER => {
                if data.len() < 16 {
                    return;
                }
                let surface = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let x = i32::from_ne_bytes(data[8..12].try_into().unwrap_or([0; 4]));
                let y = i32::from_ne_bytes(data[12..16].try_into().unwrap_or([0; 4]));
                let serial = self.alloc_serial();
                self.send_pointer_enter(surface, x, y, serial);
            }
            ipc::WEVT_POINTER_LEAVE => {
                if data.len() < 8 {
                    return;
                }
                let surface = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let serial = self.alloc_serial();
                self.send_pointer_leave(surface, serial);
            }
            ipc::WEVT_POINTER_MOTION => {
                if data.len() < 20 {
                    return;
                }
                let surface = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let x = i32::from_ne_bytes(data[8..12].try_into().unwrap_or([0; 4]));
                let y = i32::from_ne_bytes(data[12..16].try_into().unwrap_or([0; 4]));
                let time = u32::from_ne_bytes(data[16..20].try_into().unwrap_or([0; 4]));
                self.send_pointer_motion(surface, x, y, time);
            }
            ipc::WEVT_POINTER_BUTTON => {
                if data.len() < 12 {
                    return;
                }
                let button = data.get(1).copied().unwrap_or(0);
                let pressed = data.get(2).copied().unwrap_or(0) != 0;
                let surface = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let time = u32::from_ne_bytes(data[8..12].try_into().unwrap_or([0; 4]));
                // Dismiss any active popups when the primary button is pressed
                // outside their surface (including clicks on empty space when
                // surface == 0).
                if pressed && button == 0 {
                    self.dismiss_popups_if_outside(surface);
                }
                let serial = self.alloc_serial();
                self.send_pointer_button(surface, button, pressed, time, serial);
            }
            ipc::WEVT_KEYBOARD_ENTER => {
                if data.len() < 8 {
                    return;
                }
                let modifiers = data.get(1).copied().unwrap_or(0);
                let surface = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let serial = self.alloc_serial();
                self.send_keyboard_enter(surface, modifiers, serial);
            }
            ipc::WEVT_KEYBOARD_LEAVE => {
                if data.len() < 8 {
                    return;
                }
                let surface = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let serial = self.alloc_serial();
                self.send_keyboard_leave(surface, serial);
            }
            ipc::WEVT_KEYBOARD_KEY => {
                if data.len() < 16 {
                    return;
                }
                let pressed = data.get(1).copied().unwrap_or(0) != 0;
                let modifiers = data.get(2).copied().unwrap_or(0);
                let surface = u32::from_ne_bytes(data[4..8].try_into().unwrap_or([0; 4]));
                let key = u16::from_ne_bytes(data[8..10].try_into().unwrap_or([0; 2]));
                let time = u32::from_ne_bytes(data[12..16].try_into().unwrap_or([0; 4]));
                let serial = self.alloc_serial();
                self.send_keyboard_key(surface, key, pressed, modifiers, time, serial);
            }
            _ => {}
        }
    }

    fn alloc_serial(&mut self) -> u32 {
        let serial = self.next_serial;
        self.next_serial = self.next_serial.wrapping_add(1).max(1);
        serial
    }

    /// Dismiss all active xdg_popup surfaces whose `bloom_surface_id` differs
    /// from `clicked_bloom_surface`.
    ///
    /// Called on primary button press (and any compositor toplevel action) to
    /// implement the xdg-shell rule that clicking outside a popup must send
    /// `xdg_popup.popup_done` to the owning client.  Pass `clicked_bloom_surface = 0`
    /// for clicks on empty screen space (no focused surface).
    fn dismiss_popups_if_outside(&mut self, clicked_bloom_surface: u32) {
        for client in self.clients.values_mut() {
            let popup_surfaces = client.popup_bloom_surface_ids();
            for popup_surface_id in popup_surfaces {
                if popup_surface_id == clicked_bloom_surface {
                    // Click landed on this popup — do not dismiss it.
                    continue;
                }
                if let Some(cmds) = client.blossom.dismiss_popup_for_surface(popup_surface_id) {
                    dispatch::send_blossom_commands(client, &cmds, self.cmd_write);
                    info!(
                        "wayland-server: xdg_popup.popup_done surface={} (click outside or chrome action)",
                        popup_surface_id
                    );
                }
            }
        }
    }

    fn send_pointer_enter(&mut self, surface: u32, x: i32, y: i32, serial: u32) {
        for client in self.clients.values() {
            let Some(pointer) = client.pointer_object() else {
                continue;
            };
            let Some(wl_surface) = client.wl_surface_for_bloom_surface(surface) else {
                continue;
            };
            let mut payload = Vec::new();
            payload.extend_from_slice(&serial.to_ne_bytes());
            payload.extend_from_slice(&wl_surface.to_ne_bytes());
            payload.extend_from_slice(&wl_fixed(x).to_ne_bytes());
            payload.extend_from_slice(&wl_fixed(y).to_ne_bytes());
            client.send(pointer, 0, &payload);
            break;
        }
    }

    fn send_pointer_leave(&mut self, surface: u32, serial: u32) {
        for client in self.clients.values() {
            let Some(pointer) = client.pointer_object() else {
                continue;
            };
            let Some(wl_surface) = client.wl_surface_for_bloom_surface(surface) else {
                continue;
            };
            let mut payload = Vec::new();
            payload.extend_from_slice(&serial.to_ne_bytes());
            payload.extend_from_slice(&wl_surface.to_ne_bytes());
            client.send(pointer, 1, &payload);
            break;
        }
    }

    fn send_pointer_motion(&mut self, surface: u32, x: i32, y: i32, time: u32) {
        for client in self.clients.values() {
            let Some(pointer) = client.pointer_object() else {
                continue;
            };
            if client.wl_surface_for_bloom_surface(surface).is_none() {
                continue;
            }
            let mut payload = Vec::new();
            payload.extend_from_slice(&time.to_ne_bytes());
            payload.extend_from_slice(&wl_fixed(x).to_ne_bytes());
            payload.extend_from_slice(&wl_fixed(y).to_ne_bytes());
            client.send(pointer, 2, &payload);
            break;
        }
    }

    fn send_pointer_button(
        &mut self,
        surface: u32,
        button: u8,
        pressed: bool,
        time: u32,
        serial: u32,
    ) {
        for client in self.clients.values() {
            let Some(pointer) = client.pointer_object() else {
                continue;
            };
            if client.wl_surface_for_bloom_surface(surface).is_none() {
                continue;
            }
            let mut payload = Vec::new();
            payload.extend_from_slice(&serial.to_ne_bytes());
            payload.extend_from_slice(&time.to_ne_bytes());
            payload.extend_from_slice(&evdev_button(button).to_ne_bytes());
            payload.extend_from_slice(&(if pressed { 1u32 } else { 0u32 }).to_ne_bytes());
            client.send(pointer, 3, &payload);
            break;
        }
    }

    fn send_keyboard_enter(&mut self, surface: u32, modifiers: u8, serial: u32) {
        for client in self.clients.values_mut() {
            let Some(keyboard) = client.keyboard_object() else {
                continue;
            };
            let Some(wl_surface) = client.wl_surface_for_bloom_surface(surface) else {
                continue;
            };
            let mut payload = Vec::new();
            payload.extend_from_slice(&serial.to_ne_bytes());
            payload.extend_from_slice(&wl_surface.to_ne_bytes());
            payload.extend_from_slice(&crate::wayland::wire::encode_array(&[]));
            client.send(keyboard, 1, &payload);
            send_keyboard_modifiers(client, keyboard, modifiers, serial);
            break;
        }
    }

    fn send_keyboard_leave(&mut self, surface: u32, serial: u32) {
        for client in self.clients.values() {
            let Some(keyboard) = client.keyboard_object() else {
                continue;
            };
            let Some(wl_surface) = client.wl_surface_for_bloom_surface(surface) else {
                continue;
            };
            let mut payload = Vec::new();
            payload.extend_from_slice(&serial.to_ne_bytes());
            payload.extend_from_slice(&wl_surface.to_ne_bytes());
            client.send(keyboard, 2, &payload);
            break;
        }
    }

    fn send_keyboard_key(
        &mut self,
        surface: u32,
        key: u16,
        pressed: bool,
        modifiers: u8,
        time: u32,
        serial: u32,
    ) {
        for client in self.clients.values_mut() {
            let Some(keyboard) = client.keyboard_object() else {
                continue;
            };
            if client.wl_surface_for_bloom_surface(surface).is_none() {
                continue;
            }
            if client.keyboard_modifiers != modifiers {
                send_keyboard_modifiers(client, keyboard, modifiers, serial);
            }
            let Some(evdev_key) = evdev_key(key) else {
                return;
            };
            let mut payload = Vec::new();
            payload.extend_from_slice(&serial.to_ne_bytes());
            payload.extend_from_slice(&time.to_ne_bytes());
            payload.extend_from_slice(&evdev_key.to_ne_bytes());
            payload.extend_from_slice(&(if pressed { 1u32 } else { 0u32 }).to_ne_bytes());
            client.send(keyboard, 3, &payload);
            break;
        }
    }

    // ── Remove client ────────────────────────────────────────────────────

    fn remove_client(&mut self, token: WaitToken) {
        if let Some(client) = self.clients.remove(&token) {
            debug!("wayland-server: client disconnected fd={}", client.fd);

            // Clean up all scene surfaces owned by this client.
            // Collect unique bloom_surface_ids to avoid redundant destroy commands.
            let mut destroyed = Vec::new();
            for entry in client.objects.values() {
                let bloom_id = match entry {
                    crate::wayland::client::ObjectEntry::Surface { bloom_surface_id, .. } => {
                        *bloom_surface_id
                    }
                    crate::wayland::client::ObjectEntry::XdgSurface { bloom_surface_id } => {
                        *bloom_surface_id
                    }
                    crate::wayland::client::ObjectEntry::LayerSurface {
                        bloom_surface_id, ..
                    } => *bloom_surface_id,
                    _ => 0,
                };
                if bloom_id != 0 && !destroyed.contains(&bloom_id) {
                    let msg = ipc::encode_destroy_surface(bloom_id);
                    let _ = stem::syscall::port_send_all(self.cmd_write, &msg);
                    destroyed.push(bloom_id);
                }
            }

            let _ = vfs_close(client.fd);
            self.svc.remove(token);
        }
        // If the clipboard owner disconnected, clear the selection for all others.
        if self.clipboard_owner == Some(token) {
            self.clipboard_owner = None;
            let prev_source = self.clipboard_source_obj;
            self.clipboard_source_obj = 0;
            self.clipboard_mime_types = Vec::new();
            debug!("wayland-server: clipboard owner disconnected, clearing selection");
            // Notify remaining clients that the selection is cleared.
            if prev_source != 0 {
                self.broadcast_selection_null();
            }
        }
    }

    // ── Clipboard helpers ────────────────────────────────────────────────

    /// Allocate the next server-assigned Wayland object ID.
    ///
    /// Server-assigned IDs must be in the range [0xFF000001, 0xFFFFFFFF].
    fn alloc_server_id(&mut self) -> u32 {
        let id = self.next_server_id;
        // Wrap within the server-assigned range before reaching 0xFFFFFFFF.
        self.next_server_id = if id >= 0xFFFF_FFFE { 0xFF00_0001 } else { id + 1 };
        id
    }

    /// Handle `wl_data_device.set_selection`:
    /// update clipboard state and broadcast the new selection to all other
    /// clients that have a bound `wl_data_device`.
    fn handle_clipboard_set(
        &mut self,
        owner_token: WaitToken,
        source_obj: u32,
        mime_types: Vec<String>,
    ) {
        // Cancel the previous selection source (send wl_data_source.cancelled).
        if let Some(prev_tok) = self.clipboard_owner {
            let prev_source = self.clipboard_source_obj;
            if prev_source != 0 {
                if let Some(prev_client) = self.clients.get(&prev_tok) {
                    // wl_data_source.cancelled — opcode 2, no payload
                    prev_client.send(prev_source, 2, &[]);
                }
            }
        }

        if source_obj == 0 {
            // Client is clearing the selection.
            self.clipboard_owner = None;
            self.clipboard_source_obj = 0;
            self.clipboard_mime_types = Vec::new();
            info!("wayland-server: clipboard selection cleared");
            self.broadcast_selection_null();
            return;
        }

        self.clipboard_owner = Some(owner_token);
        self.clipboard_source_obj = source_obj;
        self.clipboard_mime_types = mime_types.clone();
        info!(
            "wayland-server: clipboard selection set source={} mimes={}",
            source_obj,
            mime_types.len()
        );

        // Broadcast the new selection to all OTHER clients that have a data device.
        let tokens: Vec<WaitToken> = self.clients.keys().copied().collect();
        for tok in tokens {
            if tok == owner_token {
                continue;
            }
            self.send_selection_offer(tok, &mime_types);
        }
    }

    /// Send `wl_data_device.selection(null)` to all clients with a data device.
    fn broadcast_selection_null(&mut self) {
        let tokens: Vec<WaitToken> = self.clients.keys().copied().collect();
        for tok in tokens {
            if let Some(client) = self.clients.get(&tok) {
                if let Some(dd_obj) = client.data_device_obj {
                    // wl_data_device.selection(id: null) — opcode 5
                    client.send(dd_obj, 5, &0u32.to_ne_bytes());
                }
            }
        }
    }

    /// Create a new `wl_data_offer` for `receiver_token` and deliver the
    /// current clipboard MIME types, then send `wl_data_device.selection`.
    fn send_selection_offer(&mut self, receiver_token: WaitToken, mime_types: &[String]) {
        use crate::wayland::wire::encode_string;

        let client = match self.clients.get(&receiver_token) {
            Some(c) => c,
            None => return,
        };
        let dd_obj = match client.data_device_obj {
            Some(d) => d,
            None => return,
        };

        let offer_id = self.alloc_server_id();

        // Register the data_offer object on this client.
        if let Some(client) = self.clients.get_mut(&receiver_token) {
            client.insert(offer_id, crate::wayland::client::ObjectEntry::DataOffer);

            // wl_data_device.data_offer(id) — opcode 0: announce new offer
            client.send(dd_obj, 0, &offer_id.to_ne_bytes());

            // wl_data_offer.offer(mime_type) — opcode 0: for each MIME type
            for mime in mime_types {
                client.send(offer_id, 0, &encode_string(mime));
            }

            // wl_data_device.selection(offer_id) — opcode 5
            client.send(dd_obj, 5, &offer_id.to_ne_bytes());

            debug!("wayland-server: sent clipboard offer={} to client fd={}", offer_id, client.fd);
        }
    }

    /// Handle `wl_data_offer.receive`:
    /// forward the write end of the pipe to the clipboard source client so
    /// it can write the requested data.
    fn handle_offer_receive(&mut self, write_fd: u32, mime_type: String) {
        use crate::wayland::wire::encode_string;

        let (source_client_fd, source_obj) = {
            let owner_tok = match self.clipboard_owner {
                Some(t) => t,
                None => {
                    warn!("wayland-server: data_offer.receive: no clipboard owner");
                    return;
                }
            };
            let owner = match self.clients.get(&owner_tok) {
                Some(c) => c,
                None => {
                    warn!("wayland-server: data_offer.receive: owner client gone");
                    return;
                }
            };
            (owner.fd, self.clipboard_source_obj)
        };

        // Find the source client by fd and send wl_data_source.send(mime_type, fd).
        for client in self.clients.values() {
            if client.fd == source_client_fd {
                // wl_data_source.send(mime_type: string, fd: fd) — opcode 1
                client.send_with_fds(source_obj, 1, &encode_string(&mime_type), &[write_fd]);
                debug!(
                    "wayland-server: routed data_offer.receive fd={} mime=\"{}\" to source fd={}",
                    write_fd, mime_type, source_client_fd
                );
                return;
            }
        }
        warn!(
            "wayland-server: data_offer.receive: source client fd={} not found",
            source_client_fd
        );
    }
}

fn wl_fixed(value: i32) -> i32 {
    value.saturating_mul(256)
}

fn evdev_button(button: u8) -> u32 {
    match button {
        0 => 0x110,
        1 => 0x111,
        2 => 0x112,
        other => 0x110 + other as u32,
    }
}

fn send_keyboard_modifiers(client: &mut WaylandClient, keyboard: u32, modifiers: u8, serial: u32) {
    client.keyboard_modifiers = modifiers;
    let mut payload = Vec::new();
    payload.extend_from_slice(&serial.to_ne_bytes());
    payload.extend_from_slice(&mods_depressed(modifiers).to_ne_bytes());
    payload.extend_from_slice(&0u32.to_ne_bytes());
    payload.extend_from_slice(&0u32.to_ne_bytes());
    payload.extend_from_slice(&0u32.to_ne_bytes());
    client.send(keyboard, 4, &payload);
}

fn mods_depressed(mods: u8) -> u32 {
    let mut out = 0u32;
    if mods & abi::hid::Mods::SHIFT != 0 {
        out |= 1;
    }
    if mods & abi::hid::Mods::CTRL != 0 {
        out |= 1 << 2;
    }
    if mods & abi::hid::Mods::ALT != 0 {
        out |= 1 << 3;
    }
    if mods & abi::hid::Mods::META != 0 {
        out |= 1 << 6;
    }
    if mods & abi::hid::Mods::ALTGR != 0 {
        out |= 1 << 7;
    }
    out
}

fn evdev_key(key: u16) -> Option<u32> {
    Some(match key {
        0x04 => 30,
        0x05 => 48,
        0x06 => 46,
        0x07 => 32,
        0x08 => 18,
        0x09 => 33,
        0x0A => 34,
        0x0B => 35,
        0x0C => 23,
        0x0D => 36,
        0x0E => 37,
        0x0F => 38,
        0x10 => 50,
        0x11 => 49,
        0x12 => 24,
        0x13 => 25,
        0x14 => 16,
        0x15 => 19,
        0x16 => 31,
        0x17 => 20,
        0x18 => 22,
        0x19 => 47,
        0x1A => 17,
        0x1B => 45,
        0x1C => 21,
        0x1D => 44,
        0x1E => 2,
        0x1F => 3,
        0x20 => 4,
        0x21 => 5,
        0x22 => 6,
        0x23 => 7,
        0x24 => 8,
        0x25 => 9,
        0x26 => 10,
        0x27 => 11,
        0x28 => 28,
        0x29 => 1,
        0x2A => 14,
        0x2B => 15,
        0x2C => 57,
        0x2D => 12,
        0x2E => 13,
        0x2F => 26,
        0x30 => 27,
        0x31 => 43,
        0x33 => 39,
        0x34 => 40,
        0x35 => 41,
        0x36 => 51,
        0x37 => 52,
        0x38 => 53,
        0x39 => 58,
        0x3A => 59,
        0x3B => 60,
        0x3C => 61,
        0x3D => 62,
        0x3E => 63,
        0x3F => 64,
        0x40 => 65,
        0x41 => 66,
        0x42 => 67,
        0x43 => 68,
        0x44 => 87,
        0x45 => 88,
        0x46 => 99,
        0x47 => 70,
        0x48 => 119,
        0x49 => 110,
        0x4A => 102,
        0x4B => 104,
        0x4C => 111,
        0x4D => 107,
        0x4E => 109,
        0x4F => 106,
        0x50 => 105,
        0x51 => 108,
        0x52 => 103,
        0xE0 => 29,
        0xE1 => 42,
        0xE2 => 56,
        0xE3 => 125,
        0xE4 => 97,
        0xE5 => 54,
        0xE6 => 100,
        0xE7 => 126,
        _ => return None,
    })
}

fn wayland_event_len(data: &[u8]) -> Option<usize> {
    let msg_type = *data.first()?;
    let len = match msg_type {
        ipc::WEVT_BUFFER_RELEASE => 8,
        ipc::WEVT_FRAME_DONE => 12,
        ipc::WEVT_CONFIGURE_SURFACE => 16,
        ipc::WEVT_TOPLEVEL_ACTION => 16,
        ipc::WEVT_POINTER_ENTER => 16,
        ipc::WEVT_POINTER_LEAVE => 8,
        ipc::WEVT_POINTER_MOTION => 20,
        ipc::WEVT_POINTER_BUTTON => 12,
        ipc::WEVT_KEYBOARD_ENTER => 8,
        ipc::WEVT_KEYBOARD_LEAVE => 8,
        ipc::WEVT_KEYBOARD_KEY => 16,
        _ => 1,
    };
    Some(len)
}
