[package]
name = "bloom"
version = "0.1.0"
edition = "2021"

[dependencies]
stem = { path = "../../stem", features = ["rt", "global-alloc"] }
abi = { path = "../../abi" }
libdl = { path = "../libdl" }
pistil = { path = "../pistil" }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[[bin]]
name = "bloom"
path = "src/main.rs"
test = false
doctest = false
