//! Canonical public types for the `thingos.message` schema kind.
//!
//! # Schema
//!
//! ```text
//! /// The canonical inter-unit communication envelope.
//! kind thingos.message = struct {
//!   kind:    ref<thingos.kind>,
//!   payload: bytes,
//! }
//! ```
//!
//! # Role in the system
//!
//! `Message` is the **atom of communication** in ThingOS.  All future
//! coordination, lifecycle events, and IPC build on this single structure
//! rather than introducing bespoke per-subsystem event types.
//!
//! | Field     | Purpose                                                        |
//! |-----------|----------------------------------------------------------------|
//! | `kind`    | A 128-bit [`KindId`] that identifies the semantic type of the  |
//! |           | payload.  Consumers dispatch on this value.                    |
//! | `payload` | Opaque bytes carrying the typed data.  The schema identified   |
//! |           | by `kind` describes how to interpret these bytes.              |
//!
//! # Intended evolution
//!
//! This type establishes the minimal stable envelope.  Future work will layer
//! delivery semantics on top without changing this shape:
//!
//! * **Inbox** — per-unit message queues that route `Message` values to
//!   specific recipients.
//! * **Group broadcast** — fan-out delivery of a single `Message` to all
//!   members of a [`Group`](crate::group::Group).
//! * **Port-based IPC** — port endpoints that carry `Message` values
//!   across process boundaries.
//!
//! # What this is *not* (yet)
//!
//! - No sender, reply-to, or routing envelope fields.
//! - No delivery guarantees or ordering semantics.
//! - Not a replacement for kernel signals or raw port byte streams.
//!
//! # Constraints
//!
//! Do **not** introduce bespoke event or notification structs for new code
//! paths.  Use `Message` as the canonical envelope and encode semantic
//! information in the `kind` field.

/// A 128-bit identifier that names the schema kind of a [`Message`] payload.
///
/// This is a thin wrapper around the raw `[u8; 16]` KindId bytes produced by
/// the `kindc` compiler.  It is deliberately kept as an opaque byte array at
/// this layer; higher-level code that needs human-readable names should look
/// up the kind in the Kind registry.
///
/// The value `KIND_ID_THINGOS_MESSAGE` (generated by `kindc` from the
/// `thingos.message` schema) identifies the message envelope kind itself.
/// Payload kinds will have their own distinct IDs.
#[repr(C)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct KindId(pub [u8; 16]);

impl KindId {
    /// The KindId generated for `thingos.message` by `kindc`.
    ///
    /// Consumers that need to identify a message whose payload *is itself* a
    /// `thingos.message` can compare against this constant.
    pub const THINGOS_MESSAGE: KindId = KindId([
        0x71, 0x69, 0xe9, 0x49, 0xac, 0x1f, 0x62, 0xc5, 0xee, 0x79, 0xd7, 0xcf, 0x26, 0xa6, 0x4c,
        0xeb,
    ]);

    /// The KindId generated for `thingos.job.exit` by `kindc`.
    ///
    /// Identifies the payload of a `JobExit` notification message delivered
    /// through the canonical Message/Inbox path.  Receivers dispatch on this
    /// value to recognise job-exit lifecycle events.
    pub const THINGOS_JOB_EXIT: KindId = KindId([
        0xc2, 0x60, 0x8e, 0x30, 0xff, 0xa2, 0xa2, 0xda, 0x8b, 0x96, 0x22, 0x8d, 0x3e, 0xd0, 0x11,
        0x74,
    ]);

    /// The KindId generated for `thingos.signal` by `kindc`.
    ///
    /// Identifies a typed signal notification message delivered through the
    /// canonical Inbox path.  This is the canonical asynchronous delivery
    /// vehicle for Unix-origin signals.  Receivers dispatch on this value to
    /// handle signals in their main event loop without async-signal-safe
    /// constraints.
    ///
    /// Payload encoding: `[signum: u8, sender_tid: u64 (LE), has_fault: u8,
    ///                      fault_addr: u64 (LE), rip: u64 (LE), rsp: u64 (LE)]`
    /// The trailing fault fields are present only when `has_fault == 1`.
    pub const THINGOS_SIGNAL: KindId = KindId([
        0x95, 0x34, 0x43, 0xd5, 0xfb, 0x78, 0xdf, 0xee, 0xe2, 0x6b, 0xdf, 0x35, 0x8d, 0xc9,
        0xbf, 0xe3,
    ]);

    /// The KindId generated for `thingos.signal.fault` by `kindc`.
    ///
    /// Identifies the fault-context payload nested inside a `thingos.signal`
    /// message for crash-class signals (SIGSEGV, SIGBUS, etc.).  This value
    /// is included for completeness; callers should dispatch on
    /// [`KindId::THINGOS_SIGNAL`] and inspect the embedded fault fields rather
    /// than on this identifier directly.
    pub const THINGOS_SIGNAL_FAULT: KindId = KindId([
        0x12, 0x74, 0xd1, 0xcc, 0x56, 0x95, 0x75, 0x90, 0x21, 0x9c, 0x17, 0xdd, 0x75, 0x65,
        0xa3, 0x1d,
    ]);
}

/// The canonical inter-unit communication envelope.
///
/// Corresponds to the `thingos.message` schema kind.  Every unit of
/// inter-component communication in ThingOS is expressed as a `Message`.
///
/// See the [module-level documentation](self) for usage guidelines and the
/// intended evolution of the messaging substrate.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Message {
    /// The 128-bit KindId that identifies the semantic type of `payload`.
    ///
    /// Receivers dispatch on this value to determine how to deserialize and
    /// handle the payload bytes.
    pub kind: KindId,

    /// Opaque payload bytes whose schema is identified by `kind`.
    ///
    /// The encoding is defined by the Kind referenced in `kind`.  This field
    /// remains opaque at the envelope level; only the layer that knows the
    /// concrete Kind is expected to deserialize it.
    pub payload: alloc::vec::Vec<u8>,
}

impl Message {
    /// Construct a new `Message` with the given kind identifier and payload.
    ///
    /// # Example
    ///
    /// ```
    /// # extern crate alloc;
    /// use thingos::message::{KindId, Message};
    ///
    /// let msg = Message::new(KindId::THINGOS_MESSAGE, alloc::vec![1, 2, 3]);
    /// assert_eq!(msg.kind, KindId::THINGOS_MESSAGE);
    /// assert_eq!(msg.payload, &[1, 2, 3]);
    /// ```
    pub fn new(kind: KindId, payload: alloc::vec::Vec<u8>) -> Self {
        Self { kind, payload }
    }

    /// Return `true` if the message carries no payload bytes.
    pub fn is_empty(&self) -> bool {
        self.payload.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_message_construction() {
        let kind = KindId([0u8; 16]);
        let payload = alloc::vec![10u8, 20, 30];
        let msg = Message::new(kind, payload.clone());
        assert_eq!(msg.kind, kind);
        assert_eq!(msg.payload, payload);
    }

    #[test]
    fn test_message_is_empty() {
        let kind = KindId([0u8; 16]);
        let empty = Message::new(kind, alloc::vec![]);
        assert!(empty.is_empty());

        let nonempty = Message::new(kind, alloc::vec![1]);
        assert!(!nonempty.is_empty());
    }

    #[test]
    fn test_kind_id_thingos_message_constant() {
        assert_eq!(KindId::THINGOS_MESSAGE.0, crate::kinds::KIND_ID_THINGOS_MESSAGE);
    }

    #[test]
    fn test_kind_id_thingos_job_exit_constant() {
        assert_eq!(KindId::THINGOS_JOB_EXIT.0, crate::kinds::KIND_ID_THINGOS_JOB_EXIT);
    }

    #[test]
    fn test_kind_id_thingos_signal_constant() {
        assert_eq!(KindId::THINGOS_SIGNAL.0, crate::kinds::KIND_ID_THINGOS_SIGNAL);
    }

    #[test]
    fn test_kind_id_thingos_signal_fault_constant() {
        assert_eq!(KindId::THINGOS_SIGNAL_FAULT.0, crate::kinds::KIND_ID_THINGOS_SIGNAL_FAULT);
    }

    #[test]
    fn test_message_equality() {
        let a = Message::new(KindId([1u8; 16]), alloc::vec![0xff]);
        let b = Message::new(KindId([1u8; 16]), alloc::vec![0xff]);
        let c = Message::new(KindId([2u8; 16]), alloc::vec![0xff]);
        assert_eq!(a, b);
        assert_ne!(a, c);
    }
}
