//! ipc_inbox_demo — demonstrates the typed inbox/message IPC primitive.
//!
//! # What this shows
//!
//! This demo exercises the end-to-end path for the inbox/message IPC family:
//!
//! 1. **Sender path** — `msg_send(pid, kind, payload)` delivers one typed
//!    message directly to a target process by PID.  No channel or handle
//!    exchange is required.
//!
//! 2. **Receiver path** — `InboxReceiver::try_recv()` / `recv_blocking()` pulls
//!    the next message from the calling process's kernel inbox.
//!
//! 3. **Broadcast path** — `msg_broadcast(pgid, kind, payload)` fans out a
//!    message to every member of a process group in a single syscall.
//!
//! # Architectural comparison
//!
//! | Criterion                   | Inbox (this demo)                | Channel (`ipc_service_demo`)       |
//! |-----------------------------|----------------------------------|------------------------------------|
//! | Addressing                  | PID / pgid                       | Explicit handle exchange           |
//! | Connection setup            | None                             | `port_create` + publish         |
//! | Fan-out                     | `msg_broadcast` (one syscall)    | Manual loop over handles           |
//! | Backpressure                | `EAGAIN` on sender when full     | `EAGAIN` on sender when ring full  |
//! | Best fit                    | Lifecycle events, typed dispatch | Request/reply RPC, streaming       |
//!
//! # Running
//!
//! This binary is self-contained: it delivers a message to itself using its
//! own PID.
//!
//! ```text
//! $ ipc_inbox_demo
//! ipc_inbox_demo: self-send kind=[00...00] payload=b"hello from inbox"
//! ipc_inbox_demo: received kind=[00...00] payload=b"hello from inbox"
//! ipc_inbox_demo: PASSED — round-trip OK
//! ```
//!
//! # See Also
//!
//! - `stem::syscall::message` — raw syscall wrappers
//! - `ipc_helpers::inbox` — `InboxReceiver` and convenience send functions
//! - `docs/ipc/event-vs-message.md` — design rationale
//! - `docs/ipc/convergence_strategy.md` — migration roadmap
#![no_std]
#![no_main]
extern crate alloc;

use abi::KindId;
use ipc_helpers::inbox::{InboxReceiver, send_typed, broadcast_typed};
use stem::{info, warn};

/// KindId used for the demo payload (all-zeros = untyped / raw delivery).
///
/// Real services would use a well-known KindId generated by `kindc`.  For this
/// demo we use zeroes to keep the example self-contained.
const KIND_DEMO: KindId = KindId([0u8; 16]);

/// Maximum payload size the receiver will accept.
const MAX_PAYLOAD: usize = 256;

/// Demo payload.
const PAYLOAD: &[u8] = b"hello from inbox";

#[stem::main]
fn main(_arg: usize) -> ! {
    info!("ipc_inbox_demo: starting up");

    // ── 1. Determine our own PID so we can send to ourselves ─────────────────
    let my_pid = stem::syscall::getpid() as u32;
    info!("ipc_inbox_demo: my PID = {}", my_pid);

    // ── 2. Self-send: deliver one typed message to our own inbox ─────────────
    //
    // `send_typed` is a thin wrapper around `SYS_MSG_SEND`.  No channel or
    // connection setup is needed — the kernel routes the message directly to
    // the target process's inbox.
    info!(
        "ipc_inbox_demo: sending kind=[{:02x}..] payload={} bytes to pid={}",
        KIND_DEMO.0[0],
        PAYLOAD.len(),
        my_pid,
    );

    match send_typed(my_pid, KIND_DEMO, PAYLOAD) {
        Ok(()) => info!("ipc_inbox_demo: msg_send OK"),
        Err(e) => {
            warn!("ipc_inbox_demo: msg_send FAILED: {:?}", e);
            stem::syscall::exit(1);
        }
    }

    // ── 3. Receive the message from our own inbox ─────────────────────────────
    //
    // `InboxReceiver::try_recv` is non-blocking.  Because we just sent above
    // and there are no concurrent dequeues, the message should already be
    // present.
    let rx = InboxReceiver::new(MAX_PAYLOAD);
    match rx.try_recv() {
        Ok(msg) => {
            info!(
                "ipc_inbox_demo: received kind=[{:02x}..] payload={} bytes",
                msg.kind.0[0],
                msg.payload.len(),
            );

            if msg.kind == KIND_DEMO && msg.payload.as_slice() == PAYLOAD {
                info!("ipc_inbox_demo: PASSED — round-trip OK");
            } else {
                warn!(
                    "ipc_inbox_demo: FAILED — kind or payload mismatch \
                     (got kind=[{:02x}..] payload_len={})",
                    msg.kind.0[0],
                    msg.payload.len(),
                );
                stem::syscall::exit(1);
            }
        }
        Err(e) => {
            warn!("ipc_inbox_demo: try_recv FAILED: {:?}", e);
            stem::syscall::exit(1);
        }
    }

    // ── 4. Broadcast demo: send to the default process group (pgid=1) ─────────
    //
    // In a real system this would fan out to all members of a service group.
    // Here we use pgid=1 (init group); most systems will have at least the
    // init process there.  We log the result without failing if the group
    // is empty or unreachable.
    //
    // NOTE: pgid=0 is invalid (SYS_MSG_BROADCAST returns EINVAL).  We use
    // pgid=1 which typically exists but may have no members in the demo env.
    let my_pgid = stem::syscall::getpgrp() as u32;
    info!("ipc_inbox_demo: broadcasting to pgid={}", my_pgid);

    if my_pgid != 0 {
        match broadcast_typed(my_pgid, KIND_DEMO, b"broadcast from ipc_inbox_demo") {
            Ok(report) => info!(
                "ipc_inbox_demo: broadcast OK — succeeded={} failed={}",
                report.succeeded, report.failed
            ),
            Err(e) => info!("ipc_inbox_demo: broadcast returned {:?} (expected in demo env)", e),
        }
    } else {
        info!("ipc_inbox_demo: skipping broadcast (pgid=0 is invalid)");
    }

    info!("ipc_inbox_demo: done");
    stem::syscall::exit(0);
}
