name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - trunk
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  just-test:
    name: just test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Run just test
        run: just test

  just-behave:
    name: just behave
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Run just behave
        run: just behave
